### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by balki-server** [bjoernalbers/aruba-doubles#6]
Hey there - I think you forgot to add a license to this os-repo.
A license (such as [MIT](https://github.com/bundler/bundler/blob/master/LICENSE.md)) would be ideal and will get more adoption.

Best
Balki
http://www.balki.io

**Comment by balki-server** [comment]
sorry - ignore/delete this issue.  I was looking at a different repo and ended up here for some reason.

**Comment by bjoernalbers** [comment]
No worries :-)
